allow_tpu_summary: false
best_checkpoint_eval_metric: ''
best_checkpoint_export_subdir: ''
best_checkpoint_metric_comp: higher
checkpoint_interval: 250
continuous_eval_timeout: 3600
eval_tf_function: true
eval_tf_while_loop: false
loss_upper_bound: 1000000.0
max_to_keep: 1
optimizer_config:
  ema: null
  learning_rate:
    constant:
      learning_rate: 0.0003
    type: constant
  optimizer:
    type: adam
  warmup:
    linear:
      name: linear
      warmup_learning_rate: 0.00
      warmup_steps: 0
    type: linear
recovery_begin_steps: 0
recovery_max_trials: 0
steps_per_loop: 1
summary_interval: 1
train_steps: 1
train_tf_function: true
train_tf_while_loop: true
validation_interval: 1
validation_steps: -1
validation_summary_subdir: validation
