repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8

  - repo: https://github.com/iterative/dvc
    rev: 2.18.0
    hooks:
      - id: dvc-pre-commit
        language_version: python3
        stages:
          - commit
      - id: dvc-pre-push
        language_version: python3
        stages:
          - push
      - id: dvc-post-checkout
        language_version: python3
        stages:
          - post-checkout
        always_run: true
