import setuptools

setuptools.setup(
    name="watch_recognition",
    version="0.0.1",
    author="Artur Kucia",
    author_email="author@example.com",
    description="Reading time from analog clocks",
    long_description_content_type="",
    url="https://github.com/akucia/analog-watch-recognition",
    packages=setuptools.find_packages(),
    python_requires=">=3.7",
    install_requires=[
        "numpy==1.23.1",
        "tensorflow~=2.11.0",
        "tensorflow-serving-api~=2.11.0",
        "tf-models-official",
        "keras-cv~=0.4.0",
        "pandas>=1.0.0",
        "albumentations~=1.0.3",
        "tqdm",
        "matplotlib~=3.4.3",
        "scikit-image~=0.19.3",
        "Pillow~=9.4.0",
        "scikit-learn~=1.2.1",
        "pycocotools==2.0.4",
        "click==8.1.3",
        "requests==2.27.1",
        "segmentation_models==1.0.1",
        "distinctipy==1.1.5",
        "google-cloud-storage>=2.5.0",
        "google-api-python-client>=2.58.0",
        "more-itertools~=8.14.0",
        "opencv-python",
        "dvclive==1.3.2",
    ],
)
