version: '3'
services:
  tf-serving:
    image: tensorflow/serving:latest
    entrypoint:
      - tensorflow_model_server
      - --port=8500
      - --rest_api_port=8501
      - --model_config_file=/models.conf
#      - --file_system_poll_wait_seconds=60
#      - --model_config_file_poll_wait_seconds=60
      - --num_load_threads=4
      - --xla_cpu_compilation_enabled=true
      - --prefer_tflite_model=true
#    environment:
#        - TF_CPP_MIN_LOG_LEVEL=1
#        - TF_CPP_VMODULE="http_server=1"
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ../exported_models/detector/serving:/models/detector/1
      - ../exported_models/detector/lite16:/models/detector/lite16/1
      - ../exported_models/detector/lite8:/models/detector/lite8/1
      - ../exported_models/segmentation/hands/default:/models/hands/1
      - ../exported_models/segmentation/hands/lite:/models/hands/lite/1
      - ../models/keypoint:/models/keypoint/1
      - ./models.conf:/models.conf
